### ISSUE TITLE
pre-buit version

### ISSUE THREAD

**Issue by dberardo-com** [brianc/node-pg-native#118]
is it possible to install a pre-built version of this package without the need of adding all requirements (make, g++, etc .. ) ? 

if not, is it possible to build the package and then remove the dependencies, such as g++, etc after it has been built ? what would need to remain on the machine in order fr this lib to work ? i assume that:

* the node_modules/pg-native folder needs to be preserved
* the machine needs to have "postgresql-client" (psql) installed

can this work ? 

background: trying to use this module in a docker container

**Comment by charmander** [comment]
- not pre-built by the maintainer, but you can pre-build it yourself
- yes
- libpq
- yes
- no
- yes

**Comment by dberardo-com** [comment]
thanks for the answer. i assume therefore that it is enough to have only libpq installed on the node, and copy over the node_modules folder, for the pg-native package to run.

so my indication above was correct, except that instead of install postgresql-client, one needs libpq

right ?

**Comment by dberardo-com** [comment]
this should be the case indeed: https://github.com/brianc/node-pg-native/issues/72#issuecomment-883987543
