### ISSUE TITLE
incompatibility issue with sequelize v6 ?

### ISSUE THREAD

**Issue by dberardo-com** [brianc/node-pg-native#119]
i am getting this error: this.lib.Client is not a constructor when using pg-native with sequelize. more details here: https://github.com/sequelize/sequelize/issues/16458

is this normal ?

**Comment by charmander** [comment]
This package is used via pg. Try `pg.native` (where `pg = require('pg')` or equivalent).

**Comment by dberardo-com** [comment]
according to this table pg-native is supported by sequelize: https://sequelize.org/releases/

has that changed?

**Comment by charmander** [comment]
`pg.native` is how pg-native is exposed with a common API.

**Comment by dberardo-com** [comment]
thanks a lot, now the error has changed:

Cannot read properties of undefined (reading 'on')

probably this is due to some join operation i am using in the query ? :-/
