### ISSUE TITLE
cannot install on windows 8.1

### ISSUE THREAD

**Issue by abenhamdine** [brianc/node-pg-native#14]
Hi Brian, and kudos for the awesome work on node-pg.

I try for the first time to use native bindings, but I get an error on install, wether I have root acces or no  (npm is version 2.1.11) :

    Your environment has been set up for using Node.js 0.10.35 (x64).    

    C:\Windows\System32>npm install pg-native -save
    \
    > libpq@1.3.1 install C:\Windows\System32\node_modules\pg-native\node_modules\libpq
    > node-gyp rebuild    
    

    C:\Windows\System32\node_modules\pg-native\node_modules\libpq>node "C:\Users\Arnaud\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_
    modules\node-gyp\bin\node-gyp.js" rebuild
    'pg_config' is not recognized as an internal or external command,
    operable program or batch file.
    gyp: Call to 'pg_config --includedir' returned exit status 1. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Arnaud\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Windows_NT 6.2.9200
    gyp ERR! command "node" "C:\\Users\\Arnaud\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Windows\System32\node_modules\pg-native\node_modules\libpq
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok
    npm ERR! Windows_NT 6.2.9200
    npm ERR! argv "node" "C:\\Users\\Arnaud\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pg-native" "-save"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.1.11
    npm ERR! code ELIFECYCLE    

    npm ERR! libpq@1.3.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the libpq@1.3.1 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the libpq package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls libpq
    npm ERR! There is likely additional logging output above.    

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Windows\System32\npm-debug.log    

    C:\Windows\System32>

**Comment by abenhamdine** [comment]
I close it because I think it has nothing to do with node-pg-native.
It's an error related to VS install on Windows

**Comment by UnknownHero** [comment]
Get same error on Ubuntu 14.04

**Comment by brianc** [comment]
Do you have libpq and all the required C dependencies in your path? There's
a bit of description in the readme for this repo on the things you need.
