### ISSUE TITLE
Cannot install using iojs v1.3.1

### ISSUE THREAD

**Issue by 3m0** [brianc/node-pg-native#15]
Hello,
Whenever I try to install pg-native in my current iojs installation, I always end up getting the following output:
## 

|
|

> libpq@1.5.1 install /home/user/iojs/myapp/node_modules/pg-native/node_modules/libpq
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:397:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:287:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/iojs/myapp/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v1.3.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "pg-native"
npm ERR! node v1.3.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.5.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/iojs/myapp/npm-debug.log

**Comment by ruimarinho** [comment]
@3m0 try updating your io.js version. The package currently compiles fine with v2.0.1 (with some deprecation warnings, but that's ok).

**Comment by zaggino** [comment]
@ruimarinho I've got the same error as above on `v2.0.1` (windows, x64)

**Comment by brianc** [comment]
Most install errors are related to libpq or postgres client libs not being
available.  Is your environment set up all correctly?

**Comment by zaggino** [comment]
well, `pg_config` is in the path together with the all of the `bin` directory contents
```
C:\Users\zaggino>pg_config
BINDIR = C:/tools/pgsql/bin
DOCDIR = C:/tools/pgsql/doc
HTMLDIR = C:/tools/pgsql/doc
INCLUDEDIR = C:/tools/pgsql/include
PKGINCLUDEDIR = C:/tools/pgsql/include
INCLUDEDIR-SERVER = C:/tools/pgsql/include/server
LIBDIR = C:/tools/pgsql/lib
PKGLIBDIR = C:/tools/pgsql/lib
LOCALEDIR = C:/tools/pgsql/share/locale
MANDIR = C:/tools/pgsql/man
SHAREDIR = C:/tools/pgsql/share
SYSCONFDIR = C:/tools/pgsql/etc
PGXS = C:/tools/pgsql/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = --enable-thread-safety --enable-integer-datetimes --enable-nls --with-ldap --with-ossp-uuid --with-libxml --with-libxslt --with-tcl --with-perl --with-python
VERSION = PostgreSQL 9.4.2
```
to me the error looks like it's trying to download something (`404` request)

**Comment by zaggino** [comment]
also the error is quite different from the `libpq` problems in this issue - https://github.com/brianc/node-libpq/issues/1
