### ISSUE TITLE
Unable to install on Mac OS X 10.10.2

### ISSUE THREAD

**Issue by peek4y** [brianc/node-pg-native#17]
I tried installing by 

sudo npm install pg-native and this is what I get.

> libpq@1.5.1 install /Users/gautham/Work/omega.core/node_modules/pg-native/node_modules/libpq
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/connection.o
In file included from ../src/connection.cc:1:
In file included from ../src/addon.h:5:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:207:43: error: inline declaration of 'NanNew'
      follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Handle<T> h);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:210:1: note: previous
      definition is here
NanNew(v8::Handle<T> h) {
^
In file included from ../src/connection.cc:1:
In file included from ../src/addon.h:5:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:208:43: error: inline declaration of 'NanNew'
      follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:216:1: note: previous
      definition is here
NanNew(v8::Persistent<T> const& p) {
^
2 errors generated.
make: *** [Release/obj.target/addon/src/connection.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gautham/Work/omega.core/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v0.10.9
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.9
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.5.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gautham/Work/omega.core/npm-debug.log

**Comment by chrisanderton** [comment]
This is because libpq is requiring nan 1.5.0 - it needs libpq to require nan 1.7.0 to work..

**Comment by chrisanderton** [comment]
see https://github.com/brianc/node-libpq/issues/10

**Comment by chrisanderton** [comment]
and this pull request https://github.com/brianc/node-libpq/pull/11

**Comment by brianc** [comment]
I updated nan to the most recent version - hopefully this is fixed for you now?

**Comment by brianc** [comment]
Can you confirm you're able to install? Sorry again for the delay - I wasn't getting email notifications (I am now though!)

**Comment by peek4y** [comment]
Its OK! Thanks for working on it. ill check it out and confirm in an hour.

**Comment by peek4y** [comment]
Works fine! Thanks.
