### ISSUE TITLE
Error: Unable to set non-blocking to true

### ISSUE THREAD

**Issue by jakubknejzlik** [brianc/node-pg-native#34]
Does anybody have issues ending with this error `Unable to set non-blocking to true `? I'm running on heroku postgres, everything works fine, but after few days all connections return this message and nothing else than dyno restart helps.

I'm not saying it's problem of `pg-native`, just asking if anyone experiencing this problem too. :)

**Comment by rayros** [comment]
Me too

**Comment by jakubknejzlik** [comment]
Still happening, very occasionally. I'm switching to 1.10...hope it will help.

**Comment by jakubknejzlik** [comment]
I was running 1.09 before

**Comment by brianc** [comment]
You might want to ask postgres community about that - maybe in #postgresql
on freenode?  It's a postgres thing & not really related exactly to
pg-native.

**Comment by jakubknejzlik** [comment]
Ah, you are right. I've found this thread also: https://github.com/brianc/node-libpq/issues/28

**Comment by jakubknejzlik** [comment]
ouch...i see it's your library too :)

**Comment by brianc** [comment]
haha woe is me

**Comment by blake-regalia** [comment]
For anyone else running into this error - make sure that you are calling `client.query` **after** the async callback from `client.connect` fires
