### ISSUE TITLE
report: "the connection pool didn't work for me"

### ISSUE THREAD

**Issue by kevinburkeshyp** [brianc/node-pg-native#46]
According to @vitaly-t, attempting to swap `pg` for `pg-native` failed because the connection pool didn't work: https://github.com/brianc/node-postgres/issues/972#issuecomment-203000955

I don't have any more details, but figured it was worth reporting, to try and solicit more information.

**Comment by vitaly-t** [comment]
It is was probably too harsh to say that it doesn't work at all. But I have tons of tests failing when trying to change from the JavaScript version.

I have started looking into it in detail.

**Comment by vitaly-t** [comment]
I have finished my work with this within [pg-promise](https://github.com/vitaly-t/pg-promise). I was able to get it all to work, and released it with [version 3.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.5.0).

Although I did run into many problems while doing this:

* Different errors being reported
* Different processing for empty or null queries
* Impossible to determine JavaScript types for testing (being native)

It wouldn't fair to say that it doesn't work at all.

I think this issue should be closed here.

**Comment by vitaly-t** [comment]
@kevinburkeshyp do you want to close this issue now?

**Comment by vitaly-t** [comment]
@brianc this issue should be closed.

**Comment by brianc** [comment]
:+1: thanks!
