### ISSUE TITLE
pg-native throws errors

### ISSUE THREAD

**Issue by jtremback** [brianc/node-pg-native#48]
pg-native throws errors, while pg itself propagates the error through the callback. This is a big headache for my migration scripts, which must use pg-native because of its SSL. 

``` js
var Pool = require('pg-pool')
var PgNativeClient = require('pg-native')

import { DATABASE_URL } from '../config.js'

const pool = new Pool({
  Client: PgNativeClient,
  connectionString: DATABASE_URL,
  ssl: true
})

export function getMerchant ({ id, merchantName }, callback) {
  pool.connect(function (err, client, done) {
    if (err) { callback(err) }

    client.query('SELCT * FROM pg_catalog.pg_tables', function (err, result) {
      done()
      if (err) { return callback(err) }
      callback(null, result.rows[0].number)
    })
  })
}
```

Commenting out `Client: PgNativeClient,` changes the error behavior.

**Comment by gdarcan** [comment]
For Windows users:

copy paste all .dll files in PostgreSQL's bin directory to C:\Windows

I copied below dll's and it worked, voila!
libcurl.dll, libeay32.dll, libiconv-2.dll, libintl-8.dll, libpq.dll, libxml2.dll, libxslt.dll, ssleay32.dll, zlib1.dll

**Comment by charmander** [comment]
> Client: PgNativeClient

This isn’t correct. Use `pg.native.Client` (or just `new pg.native.Pool`).

**Comment by gdarcan** [comment]
> > Client: PgNativeClient
> 
> This isn’t correct. Use `pg.native.Client` (or just `new pg.native.Pool`).

Yes @charmander you're right, I'm sorry. I posted my comment under wrong question probably. I just solved a problem about window installation minutes ago and with the passion to help everyone, I was pasting the solution under posts.
