### ISSUE TITLE
Update dependency pg-types ?

### ISSUE THREAD

**Issue by redben** [brianc/node-pg-native#58]
current version is = 1.6
I had some issues with jsonb[] which seem to have been fixed here https://github.com/brianc/node-pg-types/pull/26/commits/c881e0aec9d950975800890b37238bdba9e459b2

**Comment by brianc** [comment]
Absolutely! Will do that tonight.

**Comment by brianc** [comment]
@redben here you go: https://github.com/brianc/node-pg-native/pull/59 :clap: 

I'll merge & push a new minor version of pg-native out here in just a min.

If you or your company benefit from node-postgres and have the means, please consider supporting my work on [Patreon](https://www.patreon.com/node_postgres).

**Comment by brianc** [comment]
published `pg-native@1.2.0`

**Comment by redben** [comment]
Thank you very much !
For the support, I sure will as soon as I get paid (i'm independent)
