### ISSUE TITLE
Support for NodeJS 4.x

### ISSUE THREAD

**Issue by jalik** [brianc/node-pg-native#65]
Hi, is there a reason why this code cannot run under node 4.x ?
Is it a limitation in the package.json or a real limitation because you use incompatible syntax in the code ?

**Comment by charmander** [comment]
pg-native *is* compatible with Node 4, and so is pg; just make sure you’re using the latest version (4.8.7).

**Comment by jalik** [comment]
Sorry, I did some tests with `pg`, node 4 and webpack, and got a lot of errors like missing modules.
I did it wrong and used gulp instead, it's now working fine. Thank you !
