### ISSUE TITLE
[Bug] Test suite fails on Travis with Node 11 (segmentation fault)

### ISSUE THREAD

**Issue by MichielDeMey** [brianc/node-pg-native#78]
Test suite on Travis using Node 11 seems to fail with a segmentation fault.
(cfr. https://travis-ci.org/brianc/node-pg-native/jobs/492244123)

Associated PR for Node 11 testing using Travis: https://github.com/brianc/node-pg-native/pull/77

**Comment by njdart** [comment]
I'm seeing a similar (maybe related?) issue with a core dump on `node:carbon-alpine` (`node@sha256:396b157f138a837de34fc48dc0ca8e37bf04d2fefc568e962acf429418950948` ) with sequelize using native postgres bindings.

It was working a week ago, in the mean time alpine has updated it's postgres (and libpq) version from 10.7-r0 to 11.2-r0

```diff
binutils [-(2.30-r5)-]{+(2.31.1-r2)+}
db [-(5.3.28-r0)-]{+(5.3.28-r1)+}
expat [-(2.2.5-r0)-]{+(2.2.6-r0)+}
g++ [-(6.4.0-r9)-]{+(8.3.0-r0)+}
gcc [-(6.4.0-r9)-]{+(8.3.0-r0)+}
gdbm (1.13-r1)
gmp (6.1.2-r1)
isl (0.18-r0)
libatomic [-(6.4.0-r9)-]{+(8.3.0-r0)+}
libbz2 (1.0.6-r6)
libc-dev (0.7.1-r0)
libffi [-(3.2.1-r4)-]{+(3.2.1-r6)+}
libgomp [-(6.4.0-r9)-]{+(8.3.0-r0)+}
libldap [-(2.4.46-r0)-]{+(2.4.47-r2)+}
libpq [-(10.7-r0)-]
[-libressl-dev (2.7.5-r0)-]{+(11.2-r0)+}
libsasl [-(2.1.26-r14)-]{+(2.1.27-r1)+}
make (4.2.1-r2)
mpc1 (1.0.3-r1)
mpfr3 (3.1.5-r1)
musl-dev [-(1.1.19-r10)-]{+(1.1.20-r4)+}
ncurses-libs [-(6.1_p20180818-r1)-]{+(6.1_p20190105-r0)+}
ncurses-terminfo [-(6.1_p20180818-r1)-]{+(6.1_p20190105-r0)+}
ncurses-terminfo-base [-(6.1_p20180818-r1)-]{+(6.1_p20190105-r0)+}
{+openssl-dev (1.1.1b-r1)+}
pkgconf [-(1.5.3-r0)-]{+(1.6.0-r0)+}
postgresql-dev [-(10.7-r0)-]{+(11.2-r0)+}
postgresql-libs [-(10.7-r0)-]{+(11.2-r0)+}
python2 [-(2.7.15-r1)-]{+(2.7.15-r3)+}
readline [-(7.0.003-r0)-]{+(7.0.003-r1)+}
sqlite-libs [-(3.25.3-r0)-]{+(3.26.0-r3)+}
```

It does, however, work fine on my development machine. There are a lot of differences between my machine, my AWS instance, and your Travis CI instance, but the one similarity I can see between your failing TravisCI pipeline and my failing AWS VM is the kernel version `4.4.0`. My dev machine is at `5.0.9`.

- TravicCI: `4.4.0-101-generic`
- Failing EC2: `4.4.0-1074-aws` (based on `ami-09677e0a6b14905b0`)
- Dev machine: `5.0.9-arch1-1-ARCH`
